version: "3.0"
name: url-shortner-app
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortner-container
    ports:
      - 5000:8001
    env_file:
      - .env.docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb-url-shortner
    ports:
      - 5555:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - url-shortner:/data/db

volumes:
  url-shortner:
    driver: local
